# Downloading Google Trends Data
Google trends data can be quite usefull to understand behavioral differences in response to a public health risk, particulary when it comes to gauging the perception of such risk.

The GGtrends module from Epigraphhub returns the results as convenient pandas dataframes.

In [17]:
from epigraphhub.data.ggtrends import (
    historical_interest,
    interest_by_region,
    interest_over_time,
)

Let's try a first search by region.

In [23]:
keywords = ["covid", "vaccine"]
interest_by_region(keywords)

               geoCode  covid  vaccine
geoName
Afghanistan         AF     61       39
Albania             AL     81       19
Algeria             DZ     96        4
American Samoa      AS     76       24
Andorra             AD     96        4
...                ...    ...      ...
Western Sahara      EH     91        9
Yemen               YE     62       38
Zambia              ZM     72       28
Zimbabwe            ZW     78       22
Åland Islands       AX     85       15

[250 rows x 3 columns]

In [11]:
interest_over_time(keywords)

            covid  vaccine  isPartial
date
2021-02-07     64       19      False
2021-02-14     59       18      False
2021-02-21     65       21      False
2021-02-28     69       27      False
2021-03-07     72       30      False
2021-03-14     73       29      False
2021-03-21     77       27      False
2021-03-28     78       30      False
2021-04-04     82       30      False
2021-04-11     77       26      False
2021-04-18     78       22      False
2021-04-25     85       28      False
2021-05-02     77       23      False
2021-05-09     74       24      False
2021-05-16     71       23      False
2021-05-23     70       21      False
2021-05-30     69       20      False
2021-06-06     63       20      False
2021-06-13     61       19      False
2021-06-20     74       24      False
2021-06-27     67       18      False
2021-07-04     69       16      False
2021-07-11     77       16      False
2021-07-18     78       18      False
2021-07-25     79       20      False
2021-08-01     89       28      False
2021-08-08     81       22      False
2021-08-15     81       21      False
2021-08-22     76       21      False
2021-08-29     72       22      False
2021-09-05     65       18      False
2021-09-12     61       18      False
2021-09-19     55       16      False
2021-09-26     55       14      False
2021-10-03     43       10      False
2021-10-10     40       11      False
2021-10-17     39       11      False
2021-10-24     37        9      False
2021-10-31     37        9      False
2021-11-07     39        9      False
2021-11-14     41        9      False
2021-11-21     45        8      False
2021-11-28     52        9      False
2021-12-05     47        8      False
2021-12-12     64       13      False
2021-12-19     77        9      False
2021-12-26     94        8      False
2022-01-02    100       10      False
2022-01-09     86        9      False
2022-01-16     92       23      False
2022-01-23     56        6      False

In [13]:
historical_interest(keywords)

HTTPSConnectionPool(host='trends.google.com', port=443): Read timed out. (read timeout=5)

Empty DataFrame
Columns: []
Index: []